Map search
guytepper/1km.co.il pull request #128
Opened 2020-10-12 17:15 UTC by guyesh

added component MapSearchAutocomplete.js - search bar for the main map.

2020-10-13 18:41 UTC, uriklar commented
@guyesh This PR looks great! 

A couple of questions:
1. Can we make it so that the search happens once the user selects from the Autocomplete dropdown? (Instead of having to click the target icon on the left)
2. You've got some merge conflicts to resolve
3. and this is a more general one, now that we have that, we don't really need the modal. We can replace the שינוי כתובת 
button with the מציאת הפגנות באזורי.

2020-10-13 19:17 UTC, guyesh commented
1. This is how it works, the icon on the left is for gps location. If you select from the dropdown the location changes.
2. I'll fix it.
3. Generally, we don't need the ' שינוי כתובת' button anymore, but we do want to display the modal to mobile users when they open the website. As it is now the modal pops up when the website is load on smartphone.
So I can remove the button but I think we should anyway show the modal on mobile.

2020-10-14 06:11 UTC, guyesh commented
I've replaced the 'שינוי כתובת' button with 'מצא הפגנות באזורי'.
*the modal is still shown when a mobile without a location in the local storage gets in.

2020-10-15 05:06 UTC, guytepper requested changes
Hi, great work! Still some work to be done though, mainly with reusing the code. 
I don't want us to maintain code for 2 components that share the same logic.

Also, some notes for the CSS:
- No need to prefix
- I want us to follow [idiomatic-css](https://github.com/necolas/idiomatic-css) style guide. I'll put `stylelint` up for us but until then, give it a quick read.
- Make sure prettier is running successfully. Has your IDE is showing you alerts when something is wrong? The missing `:` caused prettier not to run.

 
<img width="529" alt="Screen Shot 2020-10-15 at 8 02 45" src="https://user-images.githubusercontent.com/13344923/96079185-d085c400-0ebc-11eb-8eda-599bf5d83ad6.png">

Also, please remove the leftovers files & code from the Modal PR :)

2020-10-15 05:06 UTC, guytepper commented on src/App.js
> +                    {/*<Button style={{ width: '100%' }} onClick={() => dispatch({ type: 'setModalState', payload: true })}>
You can remove this 

```suggestion
```

2020-10-15 05:06 UTC, guytepper commented on src/components/Map/Map.js
> +  const addressInputRef = useRef(); //search input ref
Please make it neat:
```suggestion
  const addressInputRef = useRef(); // Search Bar ref
```

2020-10-15 05:06 UTC, guytepper commented on src/components/Map/Map.js
> +          style={{ zIndex: 1, position: 'absolute', top: '30px' }}
Why not use it on the component itself? Seems like some styles are duplicated inside

2020-10-15 05:06 UTC, guytepper commented on src/components/Map/Map.js
> +  top 30;
```suggestion
  top: 30px;
```

2020-10-15 05:06 UTC, guytepper commented on src/components/Map/Map.js
> +  position:absolute;
Space:
```suggestion
  position: absolute;
```

2020-10-15 05:06 UTC, guytepper commented on src/components/MapSearchAutocomplete/MapSearchAutocomplete.js
> +      <LocationIcon src="/icons/marker-purple.svg" alt="marker icon" />
No need for `alt` tag here
```suggestion
      <LocationIcon src="/icons/marker-purple.svg" />
```

2020-10-15 05:06 UTC, guytepper commented on src/components/MapSearchAutocomplete/MapSearchAutocomplete.js
> +      <GpsIcon src="/icons/gps.svg" alt="gps icon" onClick={() => getUserPosition()} />
```suggestion
      <GpsIcon src="/icons/gps.svg" alt="" onClick={() => getUserPosition()} />
```

2020-10-15 05:06 UTC, guytepper commented on src/components/MapSearchAutocomplete/MapSearchAutocomplete.js
> +    <Combobox style={{ position: 'absolute', zIndex: 10000, width: '100%' }} onSelect={handleSelect} aria-labelledby="demo">
What's the demo is for?

2020-10-15 05:06 UTC, guytepper commented on src/components/MapSearchAutocomplete/MapSearchAutocomplete.js
> +  -webkit-box-shadow: 14px 19px 22px -7px rgba(0,0,0,0.19);
No need for prefix.

2020-10-15 05:06 UTC, guytepper commented on src/components/MapSearchAutocomplete/MapSearchAutocomplete.js
> +      <GpsIcon src="/icons/gps.svg" alt="gps icon" onClick={() => getUserPosition()} />
`getUserPosition` is duplicated 3 places over the source code.  
Can you think of a better, reusable way to use it?

2020-10-15 05:06 UTC, guytepper commented on src/components/MapSearchAutocomplete/MapSearchAutocomplete.js
> +  };
Is there a better way to reuse all the copied code from `PlaceAutocomplete`?

2020-10-15 05:06 UTC, guytepper commented on src/components/MapSearchAutocomplete/MapSearchAutocomplete.js
> +  top 20px;
Missing `:`

2020-10-15 05:06 UTC, guytepper commented on src/components/MapSearchAutocomplete/MapSearchAutocomplete.js
> +  /*logo is white*/
Which logo? It's not clear. Also please make the comment neater :P

2020-10-15 05:06 UTC, guytepper commented on src/components/MapSearchAutocomplete/MapSearchAutocomplete.js
> +  -webkit-filter: invert(100%); /* Safari/Chrome */
No need for prefixing. 
```suggestion
```

2020-10-15 05:06 UTC, guytepper commented on src/components/Modal/Modal.js
> +  const [ImageLoaded, setImageLoaded] = useState(false);
Remove

2020-10-15 05:06 UTC, guytepper commented on src/index.css
> +
?

2020-10-15 05:06 UTC, guytepper commented on src/components/MapSearchAutocomplete/MapSearchAutocomplete.js
> +const GpsIcon = styled.img`
Change to GPSIcon
```suggestion
const GPSIcon = styled.img`
```

2020-10-15 05:06 UTC, guytepper commented on src/components/MapSearchAutocomplete/MapSearchAutocomplete.js
> +  z-index: 10001;
Can you use more distinct and clear `z-index` values? Like `100`, `200`..

2020-10-15 05:06 UTC, guytepper commented on src/components/MapSearchAutocomplete/MapSearchAutocomplete.js
> +  user-select: none;
Display correct pointer.
```suggestion
  user-select: none;
  cursor: pointer;
```

2020-10-15 05:06 UTC, guytepper commented on src/components/MapSearchAutocomplete/MapSearchAutocomplete.js
> +  padding:10px 50px;
I'll add `stylelint`, until then please follow https://github.com/necolas/idiomatic-css#declaration-order

2020-10-15 07:56 UTC, guyesh commented on src/components/MapSearchAutocomplete/MapSearchAutocomplete.js
> +  z-index: 10001;
the map is using high numbers in z-index I've put 10000 in the input field and the icon should be higher.
I'll add a note to make it clear.

2020-11-07 07:47 UTC, guytepper approved these changes
Sorry for taking so long to review this. 
I've pushed some changes to reflect the latest changes in `master`. 
Thanks! It looks great.

2020-11-07 07:48 UTC, merged