Modal sizing
guytepper/1km.co.il pull request #136
Opened 2020-10-13 13:53 UTC by guyesh

**Edited the modal size on different screens:**
 on short screens - made it high,
on high screens - made it short.
on high and thin screens (mostly phones) - fill almost all screen (with a gap).
**Edited the modal scrollbar style to fit the main page.**

2020-10-13 13:58 UTC, guyesh commented
![VID-20201013-164254](https://user-images.githubusercontent.com/61267328/95870490-36673400-0d75-11eb-9a81-95448edf4088.gif)
*does not show the new scrollbar style  only responsive modal sizes

2020-10-13 18:04 UTC, uriklar approved these changes

2020-10-14 15:10 UTC, guytepper requested changes
Thanks! Check my comments and talk to me if something's not clear.

Also, check this scenario (`1270x1020`): 
![Screen Shot 2020-10-14 at 17 58 08](https://user-images.githubusercontent.com/13344923/96008581-60d5f180-0e48-11eb-978c-3153059ad100.png)

2020-10-14 15:10 UTC, guytepper commented on src/components/Modal/Modal.js
> +    max-height: calc(100vh - 50px) !important;
Why is it needed? 
Seems like it's already declared in [line 110](https://github.com/guytepper/1km.co.il/pull/136/files#diff-869a02a1420cc0268fa726a77b96fea2f08e3bc575b1398af4af25bea39694f5R110)

2020-10-14 15:10 UTC, guytepper commented on src/components/Modal/Modal.js
> +  ::-webkit-scrollbar {
Add space between variables & style declaration.

```suggestion

  ::-webkit-scrollbar {
```

2020-10-14 15:10 UTC, guytepper commented on src/components/Modal/Modal.js
> +  scrollbar-width: thin;
Is it possible to make it clearer that those are variables?

2020-10-14 15:10 UTC, guytepper commented on src/components/Modal/Modal.js
> +  /*scrollbar*/
Let's make the section comments more neat:
```suggestion
//**** Scrollbar ****//
```

2020-10-14 15:10 UTC, guytepper commented on src/components/Modal/Modal.js
> +  @media (max-height: 700px) {
It seems here that you are chose to 'fight' against the styles that were already declared before. Why not change them directly?
You can go to the initial styles (from line `108` and below) or to the media queries (such as `min-width: 360px`) and put/exchange those styles there.

2020-10-14 15:10 UTC, guytepper commented on src/components/Modal/Modal.js
> +  ::-webkit-scrollbar-track {
Add space
```suggestion

  ::-webkit-scrollbar-track {
```

2020-10-14 15:10 UTC, guytepper commented on src/components/Modal/Modal.js
> +  ::-webkit-scrollbar-thumb {
```suggestion

  ::-webkit-scrollbar-thumb {
```

2020-10-15 16:48 UTC, merged